[package]
name = "cli-of-doom"
version = "0.1.0"
authors = ["Lee Lian Hoy <cruz@zyk3.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
console = "0.9.0"
indicatif = "0.12.0"
reqwest = "0.9.22"