[package]
name = "cli-of-doom"
version = "0.1.0"
authors = ["Lee Lian Hoy <cruz@zyk3.net>"]
edition = "2018"
default-run = "cli"

[dependencies]
clap = "*"
colored = "*"
dotenv = "*"
rand = "*"
serde = "*"
serde_json = "*"
grep = { path = "../packages/grep" }
