[package]
authors = ["Lee Lian Hoy <cruz@zyk3.net>"]
edition = "2018"
name = "cli-of-doom"
version = "0.1.0"

[dependencies]
clap = "*"
colored = "*"
dotenv = "*"
grep = {path = "../grep"}
learn = {path = "../learn"}
