[package]
authors = ["Lee Lian Hoy <cruz@zyk3.net>"]
description = "You know what the name spells!"
edition = "2021"
homepage = "https://github.com/cruz82/cli-of-doom"
name = "cli-of-doom"
version = "0.1.0"

[dependencies]
tokio = "*"
colored = "*"
dotenv = "*"
serde = "*"
serde_json = "*"
clap = { version = "*", features = ["derive"] }
grep = { path = "../grep" }
learn = { path = "../learn" }
zenu = { path = "../zenu" }
